version: "1.0"

services:
  hlds:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./cstrike/addons:/home/steam/hlds/cstrike/addons
      - ./cstrike/logs:/home/steam/hlds/cstrike/logs
      - ./cstrike/cfgs:/home/steam/hlds/cstrike/cfgs:ro
      - ./cstrike/liblist.gam:/home/steam/hlds/cstrike/liblist.gam:ro
      - ./cstrike/mapcycle.txt:/home/steam/hlds/cstrike/mapcycle.txt:ro
      - ./cstrike/server.cfg:/home/steam/hlds/cstrike/server.cfg:ro
      - ./cstrike/motd.html:/home/steam/hlds/cstrike/motd.html:ro
      - ./cstrike/maps:/home/steam/hlds/cstrike_downloads/maps:ro
      - ./cstrike/maps:/home/steam/hlds/cstrike_downloads/gfx:ro
      - ./cstrike/maps:/home/steam/hlds/cstrike_downloads/models:ro
      - ./cstrike/maps:/home/steam/hlds/cstrike_downloads/sound:ro
      - ./cstrike/maps:/home/steam/hlds/cstrike_downloads/sprites:ro
    ports:
      - "27015:27015"
      - "27015:27015/udp"
    environment:
      - RCON_PASSWORD="sap"
      - SV_PASSWORD=""
      - MAXPLAYERS="12"
      - MAPNAME="de_dust2"
